version: "3.0"

services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile\
    image: pongphisut/jclient:latest
    container_name: client
    ports:
      - "3000:3000"
